Layout/CommentIndentation:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
